name: Greetings (Workflow Name)

on: [pull_request_target, issues]

jobs:
  greeting: # job name
    runs-on: ubuntu-latest # running on 
    permissions: 
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1 # an external action being used
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }} # Usually set yourself, but think it is generated
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
